### ISSUE TITLE
[Feature] Config settings for showing queued up songs.

### ISSUE THREAD

**Issue by Uricorn** [musiqpad/mqp-server#101]
Having the ability to view the upcoming songs is an invaluable moderation tool.

If such a feature is implemented, it should be a permission that can be given to specific roles in the config.

Also it should be possible to look up specific users in the queue in the API and see what they are about to play. This feature will enable bots to warn a user if their song is against a specific rule, before they get skipped.

**Comment by DerpgonCz** [comment]
I think it was discussed before, and it was denied.

The issue is it is violating privacy of the user and if, lemme say, a user has queued up song and wants to switch, he gets these annoying notifications from some bot that whatever song is not allowed.

If you already have a bot that skips songs right when they start playing, I see no point in warning the user, annoying him and the others.

**Comment by Uricorn** [comment]
It takes time for the bot to skip it and that is assuming the bot even knows it has to skip that song, and the user has now waited hours only to get skipped and staff might have had to stop what they are doing because some trolls decided to play porn videos.

The user's privacy can be very easily 'violated' simply by the fact that I can see all of their playlists in my database and do a query to see what is next, this would just make it so I don't have to do something hacky.

When we used dubtrack people loved the feature, mods and users alike. But here we can actually make it more private by not allowing just any user to see the queue.

In our pad on musiqpad is it not likely we will annoy all the pad with the bot, since we will find a way to autoload a custom script for them so that it will 'annoy' only the specific user to tell them their song is against a rule. (I have no idea what other pads would do with the feature.)

tl;ldr people on plug already ask us to check their song to see if it's allowed, and mods have to deal with people playing troll songs that cannot be autoskipped. This makes our room better, and lives easier with almost no negative impact and is up to the pad to use or not use it.

**Comment by explodingcamera** [comment]
I think something similar should be added where if you join the queue, mods have to approve your song and you're not able to change it, only to leave the queue. This would be super useful for big communities and livestreamers who don't want to get banned on twitch.

**Comment by Uricorn** [comment]
@henr-y I agree, I wanted something like that if my pad ever got to be really really big. Though for the majority of the current pads I think this will mostly be annoying, for both mods and users.

**Comment by DerpgonCz** [comment]
I mean, you can add it yourself if you are hacky enough, I mostly talked about official pads - where you cannot see in the database.
