### ISSUE TITLE
[Feature] Allow custom favicons

### ISSUE THREAD

**Issue by Uricorn** [musiqpad/mqp-server#102]

**Comment by bgiesing** [comment]
It's already possible by replacing icons in your server. Replace `[mqp-server folder]/pads/lib/img/icon.png` with the favicon you want

**Comment by Uricorn** [comment]
Every time I upgrade my server I will have to do that again though, right?

**Comment by bgiesing** [comment]
@Uricorn yes but assuming you update via a git pull, you can just deny the changes to that file or reupload it

**Comment by explodingcamera** [comment]
I'm probably going to change the way the update script works so stuff like the favicon doesn't get overridden.
