### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by brograhamer** [musiqpad/mqp-server#112]
Hey all, it's FlannelBeard (iacon), is this project still maintained at all? Need help? 

Let me know, thanks.

**Comment by TheBanHammer** [comment]
Hi, as discussed on Discord:

Currently the team is very busy with things outside of musiqpad however we do still believe in the idea and concept. I guess you could say project is currently "taking a break".

Stick with us, version 2 will be amazing :D
