### ISSUE TITLE
Youtube search does not work

### ISSUE THREAD

**Issue by Tonysp** [musiqpad/mqp-server#15]
When trying to search for a song, it does nothing. One line in server console:
`[2016-03-31 22:23:55] SocketServer (debug) 147.32.120.95 sent: {"type":"youtubeSearch","data":{"query":"test"},"id":7}`

And few errors in Chrome client console: 
![err](https://cloud.githubusercontent.com/assets/1337608/14189810/a61702cc-f78f-11e5-8287-9a0f57048d63.png)

Also, i have SSL disabled.

**Comment by explodingcamera** [comment]
Errors are normal, they happen because of adblock/YouTube player.

**Comment by foodbandlt** [comment]
Yep, as said above those are normal.  Is there anything else in the server console that indicates why the search failed?  Have you input an API key for YouTube in the serverconfig?

**Comment by Tonysp** [comment]
I tried it in Firefox without any extensions and it still doesn't work, neither in Chrome incognito mode.
And no, nothing in server console except the line i posted before.

**Comment by DerpgonCz** [comment]
@Tonysp No errors indicating why the YouTube search would fail

Make sure your YT API key is set as "Server key" in your Google Developer Console and you have it set in your serverconfig.js files aswell.
Also make sure you have the latest version of musiqpad

**Comment by Tonysp** [comment]
Solved... I was using Browser key instead of Server key. You should specify which key to use in the example config so it doesn't happen to someone else. Thanks for the help!
