### ISSUE TITLE
[Feature] Add chat filters

### ISSUE THREAD

**Issue by crossed4** [musiqpad/mqp-server#30]
Chat filters would be a great way to see PM's, @ notifications, etc.  Adding buttons that would eliminate chats except for what is filtered for was one of the ideas.

**Comment by TheBanHammer** [comment]
@crossed4 a new PM system is already in the works and nearing completion (sneak peak attached below). We will be looking into buttons for the likes of @ notifications soon too.

![Sneak Peak of PM System](http://i.imgur.com/OV7Uokl.png)

**Comment by TheBanHammer** [comment]
Mentions filter has been added and will be released as part of the PM update:

![Mention Filter Button](http://i.imgur.com/NHGFzp4.png)
