### ISSUE TITLE
[Feature] Activate Playlist Button

### ISSUE THREAD

**Issue by TheBanHammer** [musiqpad/mqp-server#35]
Right now it's not clear to see how to activate a playlist. Adding a button would make this more use-friendly.

(Brought across from old feedback system)

**Comment by explodingcamera** [comment]
What about adding it like this:
 ![](https://i.imgur.com/THGWP4v.png)
Pressing the grey circle would activate it.

**Comment by ImGrumpy** [comment]
Adding a button at the top of the currently selected playlist to activate it (next to the rename, shuffle, export and delete icons) would help as well.

**Comment by DerpgonCz** [comment]
I'd say @henr-y 's would blend better with our design without adding more buttons to clutter the clean UI

**Comment by explodingcamera** [comment]
Added in 0d53c652bdd1b91ae76d724583123bd9312b913d
