### ISSUE TITLE
[Feature] Indicator for more Chat Messages

### ISSUE THREAD

**Issue by TheBanHammer** [musiqpad/mqp-server#36]
Notification/Indicator showing there are more text. So you know when you should scroll down.

(Brought across from old feedback system)

**Comment by explodingcamera** [comment]
Maybe do it like betterttv
![](https://i.imgur.com/hvFXoEr.png)

**Comment by TheBanHammer** [comment]
@henr-y :+1: was the sort of thing I was thinking of too.

**Comment by explodingcamera** [comment]
Added in 0d342bcd724f2b08f67f86a6891e87a995d17af9
