### ISSUE TITLE
[Bug] Config gets deleted on update

### ISSUE THREAD

**Issue by explodingcamera** [musiqpad/mqp-server#51]
If the config file is created in ./node_modules, it will be deleted when you update via npm.
You could add a config option to mqpServer.start or make db + config paths relative to the file starting the server.

**Comment by TheBanHammer** [comment]
Is something we already have on our radar.

**Comment by explodingcamera** [comment]
Yeah I know just wanted to add it here

**Comment by explodingcamera** [comment]
On hold until #39 gets finished because we need to change how the config is stored / loaded.
