### ISSUE TITLE
[Feature] Add pad name to page meta title.

### ISSUE THREAD

**Issue by Uricorn** [musiqpad/mqp-server#56]
Meta title is currently "musiqpad - join us!" for all pads.
I suggest to change it to "pad name | musiqpad".

**Comment by DerpgonCz** [comment]
For me it changes depending on pads - be it self-hosted or those using our FE

**Comment by TheBanHammer** [comment]
@Uricorn The page title gets set properly when the room information is loaded from the socket. I do believe that the default should be changed however that is another issue.

In regards to what this actually affects it is mostly search engines and social media sites. These should have been fixed based on the changes that we have made for: #57
