### ISSUE TITLE
[Feature] Add support for Open Graph.

### ISSUE THREAD

**Issue by Uricorn** [musiqpad/mqp-server#57]
Facebook and other websites rely on [Open Graph](http://ogp.me/) to generate a rich preview of a website.

How it currently looks:
![capture](https://cloud.githubusercontent.com/assets/5571265/14754485/5559a11c-08e4-11e6-82ec-174768b780e3.png)

It will look much better with the following:
`<meta property="og:title" content="Meta Title Here"/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="https://sh.musiqpad.com/p/padurl/"/>
<meta property="og:image" content="user defined image here"/>
<meta property="og:description" content="user defined description here"/>`

**Comment by foodbandlt** [comment]
This is a complicated issue with the hosted frontend because those attributes would not be set until after page load and after javascript has executed.  We could try baking them into the page initially, but it would required templating and I don't know what overhead that would bring with it for our webserver.

Perhaps @TheBanHammer could provide some insight on it.  He setup the webserver, so he might have a better idea of how we could implement this.  I don't remember what webserver we used for the hosted frontend.

**Comment by foodbandlt** [comment]
In addition to that, if we do go through with templating this into the hosted frontend, this might make getting pad configs to the frontend easier for hosted frontend.  At the moment there are some weird caching issues with pad configs because of how it's delivered.

**Comment by TheBanHammer** [comment]
@foodbandlt I've been looking into this with a fair amount of thought. Currently I have an idea however it needs discussing internally before it goes ahead.

**Comment by TheBanHammer** [comment]
This has been added now. OpenGraph will work on both shortened and full length urls:

![Full Length URL](http://i.imgur.com/z3oIImk.png)

![Shortened URL](http://i.imgur.com/pSS2Up0.png)

**Comment by Uricorn** [comment]
Will there be a way to customize the image?

Also the default image doesn't meet the optimal specs for Facebook.
I recommend using an image that is 1200x628 in PNG format. That is UNDER 900 Kb.

tinypng.com is a great compression service if you need one.

The preview will be nicer, something like this.
![capture](https://cloud.githubusercontent.com/assets/5571265/14830589/1570ec5e-0bfa-11e6-921c-324917181928.png)

**Comment by DerpgonCz** [comment]
We will probably be customizing it more, like allow pads to add their own image like with background

**Comment by Uricorn** [comment]
This does not work on pad links that aren't mqp.io or musiqpad.com

Also should I open an issue regarding the og:image?

**Comment by TheBanHammer** [comment]
@Uricorn it is only supported on the official links as it isnt handled by the web server directly.

I would recommend opening a generic feature request for Open Graph improvements and customization for the central server.
