### ISSUE TITLE
[Feature] Pad search in lobby.

### ISSUE THREAD

**Issue by Uricorn** [musiqpad/mqp-server#58]

**Comment by DerpgonCz** [comment]
Added, waiting for proper CSS to be applied

**Comment by explodingcamera** [comment]
Css is done, will be pushed soon.

**Comment by Uricorn** [comment]
The search results can be a bit funny.
![capture](https://cloud.githubusercontent.com/assets/5571265/14798413/2b4aab74-0b40-11e6-9e4e-00e5f2e6c1b4.png)

**Comment by henr-y** [comment]
are you talking about the search bar?

**Comment by DerpgonCz** [comment]
@uricorn sadly, those pads have special characters in their slugs and cannot be hidden because they cannot be targeted by jQuery. We will be changing the policy so these pads will have their keys revoked (probably)

**Comment by Uricorn** [comment]
@DerpgonCz, I meant that the results aren't always what you expect.

For instance, I search for my pad "AnimeMusic.me and Japanese Music", when I search "Anime" it finds it. When I search "Jap" or "Music" it doesn't show.

**Comment by DerpgonCz** [comment]
Hmm, strange, I will check it when I get back home

**Comment by ImGrumpy** [comment]
Looks like it's a case sensitivity issue to me.  If you type your search in the exact case of the room name, it works.  It should be case insensitive, obviously.

**Comment by DerpgonCz** [comment]
@ImGrumpy Yeah, I just arrived at the PC, it is fixed
