### ISSUE TITLE
Imported playlist (from Dubtrack) has no songs or doubles after refresh

### ISSUE THREAD

**Issue by ImGrumpy** [musiqpad/mqp-server#62]
http://pastebin.com/Caf06Vvm

This playlist appears to import correctly into a list named "Rock" with 308 songs.  List is usable, but after a refresh the list is empty.  User who reported it guesses that it has to do with the length as shorter lists have worked correct for him.  I tested the list and the same thing happened to me.

**Comment by ImGrumpy** [comment]
User reports that splitting the list into two smaller lists fixes the issue.

**Comment by ImGrumpy** [comment]
Another user was having a similar issue... so I had them try splitting it into 2 (both under 200) with mixed results.  One of the two lists worked fine, but the smaller of the two (about 75 songs) actually doubled when they tried a refresh.

The doubling complaint is something I've heard from a few different users.

**Comment by TheBanHammer** [comment]
Another troublesome playlist for testing with: http://pastebin.com/bnNjtN3m
