### ISSUE TITLE
[Suggestion] Placement and colors of buttons under video.

### ISSUE THREAD

**Issue by Uricorn** [musiqpad/mqp-server#65]
This suggestion is purely about design, and as such should be treated as a personal opinion.

Regarding Placement:
I suggest either placing the most commonly used buttons to the left, or keeping the 'upvote' and 'downvote' symmetrical to each other since they are a "pair".
- Placement Reasoning:
  English is read left to right, as such most User Interfaces are usually designed with the important/most used actions starting from the left.

Symmetry is an important design aspect.

Colors:
I think that the 'snooze' and 'join' button colors should be changed.

The 'join' button should be a more inviting and friendly color, while the 'snooze' button should be a more red or orange color.
- Color Reasoning:
  You want people to click the 'join' button, so it should look inviting. It's currently orange which is similar to a warning sign.

The 'snooze' action is a bit negative at times, similar to downvoting the song. As such, it makes sense that they should be a similair color. Additionally, purple is already taken by the 'grab' button.

Examples:
![capture](https://cloud.githubusercontent.com/assets/5571265/14833371/9e42b230-0c07-11e6-8450-c28f8519c579.png)
![capture](https://cloud.githubusercontent.com/assets/5571265/14833377/a683a99a-0c07-11e6-90c0-2bc3e06d375a.png)

**Comment by foodbandlt** [comment]
Let's get @marcianoloko in here.

**Comment by DerpgonCz** [comment]
I am pretty used to how it is now. The color change is nice, but I wouldn't personally move the buttons.

If they are going to be changed in any way, there will either be an option to change it to the "new style" or they will be "unlockable" and able to be reordered

**Comment by ngustavo** [comment]
No move. Maybe change colors.
