### ISSUE TITLE
[Bug] Private chat with longer messages

### ISSUE THREAD

**Issue by RwbyChan2** [musiqpad/mqp-server#76]
When you have long messages in a private chat, then it will screw up the messages list:
http://prntscr.com/b1bjge

Solution:
`.pm-user {
    height: 60px;
    cursor: pointer;
    word-break: break-all; 
    overflow: hidden; 
}`

adding a word-break and an overflow to the css from pm-user will solve this, atleast it did for me

**Comment by explodingcamera** [comment]
Yes, i've found the bug but your solution doesn't work correctly. Fixed in 7c20adbf6ce96ad49ea015046eafa49dbc8e081f
