### ISSUE TITLE
[SUGGESTION] Command to start an update.

### ISSUE THREAD

**Issue by ImExiled** [musiqpad/mqp-server#84]
Hello!

Maybe add a Chat or Console command to start updating. Maybe make it give users a minute or two warning or something.

Like /startupdate as owner or someone with permissions, where it then gives a message to all users that the server will go down after a song or a few minutes to update, and return within 5 minutes etc.

Thanks,
-CSxKING

**Comment by explodingcamera** [comment]
- [X] Update script
- [ ] ~~Update Command~~

**Comment by explodingcamera** [comment]
I'm against an cmd to update. This should be done via the admin panel #39.

**Comment by DerpgonCz** [comment]
Updates will be done via the admin panel, command is therefore not needed
