### ISSUE TITLE
Played songs do not move from top

### ISSUE THREAD

**Issue by tnws** [musiqpad/mqp-server#87]
to reproduce:
- play a song
- transition the song somehow (wait for it to end, skip, etc)
- refresh
- song should still be at the top of playlist

**Comment by tnws** [comment]
To add on: it's just any playlist changes. I logged on, shuffled my playlist, refreshed, and there was no movement from the song positions.

**Comment by TheBanHammer** [comment]
Please could you provide some information such as the pad you were using and the database type.

**Comment by tnws** [comment]
The pad was self-hosted, running version `0.6.5`; database:

`$ mysql --version
mysql  Ver 14.14 Distrib 5.5.49, for debian-linux-gnu (x86_64) using readline 6.3`

However, in 764a5f752e48a41a873d08c810fe50aa65f026ca, it was fixed for me.
