### ISSUE TITLE
[Feature] Extra characters in name

### ISSUE THREAD

**Issue by RwbyChan2** [musiqpad/mqp-server#88]
Maybe allowing users to have more characters to use in their username? Such as a space for example?

**Comment by TheBanHammer** [comment]
In my opinion I don't think this should be a thing. It would make things like mentions much harder.

**Comment by ImGrumpy** [comment]
Extra characters maybe, but definitely not spaces.  Agree with TBH 100%.  Spaces also makes it very hard for a bot to parse out commands aimed at a particular user.

**Comment by DerpgonCz** [comment]
More characters as in character count - no problem with that, but having a long usernames makes it

a) Harder to remember
b) Makes it too _fancy_ (and standing out among the others)
c) There would be problems with some names being too long and thus filling up most of the row - which does not look great at all

You can change checking username validity (and thus removing any limits) in https://github.com/musiqpad/mqp-server/blob/master/socketserver/database_util.js#L13 but, of course, on your own responsibility

That being said, we will most likely be keeping the 20 alphanum with _ and - characters limit

**Comment by RwbyChan2** [comment]
Okey
