### ISSUE TITLE
[Bug] Recovery password

### ISSUE THREAD

**Issue by RwbyChan2** [musiqpad/mqp-server#90]
When trying to recover a password, I get this error

> There was an error with sending recovery email, please contact the pad owner
> While I have allowrecovery on true and at the 'email' part there is a valid email filled in.

Also when trying to recover a password, the system will update the database, adding something at recovery and recovery_timeout
So I guess it's kinda bugged?

Also an idea: maybe add a feature to change your password?

**Comment by DerpgonCz** [comment]
What pad were you trying to recover the email on?

**Comment by RwbyChan2** [comment]
On http://pad.nightcore-fantasia.net/

**Comment by DerpgonCz** [comment]
It was an issue with config
