### ISSUE TITLE
[Feature] Add an "Always Active" playlist

### ISSUE THREAD

**Issue by bgiesing** [musiqpad/mqp-server#97]
If somebody joins a pad with nobody else online, the pad owner should be allowed to set a playlist that will play till somebody adds stuff. For instance, I'm using my pad like an Internet TV channel and I can't always be online (sleep, not home, etc.). If somebody enters who doesn't know what to do, they are just staring a blank window since I'm not online so it's not playing anything. With this, I could add a playlist with promos and/or a tutorial on how to add stuff.

Now this is not an "always playing" playlist meaning that it's not going to be playing when nobody is there (wasting server bandwidth), instead it's more like a special user with a playlist (separate from a user account) that would start playing if somebody joins and nobody else is in the queue.

**Comment by TheBanHammer** [comment]
I don't think this should be included inside the base musiqpad server. This stuff could be handled by a bot maybe?

**Comment by ImGrumpy** [comment]
It could very easily be handled with a bot.  I used to do this with my old Turntable.fm room to help keep it alive.

**Comment by bgiesing** [comment]
@ImGrumpy That's the thing, I don't want to keep it alive (as that would waste all my free server quota) but instead it would only start playing if somebody joins the room that's not DJing. So it's like if you auto-queued the second you logged in but instead of it being you (and you having to be in the room), it would be a playlist in the serverconfig run by the server.

That's why a bot wouldn't work because a bot would keep the server alive, right? And that's the opposite of what I'm asking.

**Comment by ImGrumpy** [comment]
A bot can do that too.  Easy enough for a bot to tell if there's anyone in the pad, to hop on stage when needed and to leave the stage when there's no one there anymore.

**Comment by bgiesing** [comment]
@ImGrumpy Ah, wasn't sure but if a bot would work, I guess the next question is finding somebody willing to make a bot that could do that. Thanks for the help!

**Comment by DerpgonCz** [comment]
Closing, a bot can do this easily.
