### ISSUE TITLE
[Bug] Disconnects when active on Heroku's Free Tier

### ISSUE THREAD

**Issue by bgiesing** [musiqpad/mqp-server#98]
When using it on Heroku's Free Tier (which stops the server if nobody is active for 20 mins), it disconnects even if somebody is logged in, watching something, and actively adding stuff). This makes it impossible to watch videos over a certain length as you have to start from the beginning when it disconnects and can't skip to the point it stopped.

**Comment by TheBanHammer** [comment]
Is this an issue with musiqpad specifically or running musiqpad on Heroku? If it is the latter what is Heroku expecting to detect in order to determine activity?

**Comment by bgiesing** [comment]
@TheBanHammer That's the problem, I just don't know for either question.

**Comment by explodingcamera** [comment]
Heroku checks for http requests, and doesn't care about websocket connections. More infos: https://devcenter.heroku.com/articles/free-dyno-hours. You could write a bot that requests the page every 20 mins or so (which is probably against their tos) or switch to openshift or a paid server.
